config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_one :purchase, dependent: :destroy

  has_one_attached :photo
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :items, dependent: :destroy
  has_many :purchases, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.all
  end

  def show; end

  def edit; end

  def update
    @item.update(item_params)
    redirect_to item_path(@item)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    @item.user = current_user
    if @item.save
      redirect_to item_path(@item)
   else
      render :new
   end
  end

  def destroy
    @item.destroy
    redirect_to items_path
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :description, :location, :credit, :image)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_form.html.erb
<%= simple_form_for @item do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :credit, as: :numeric %>
  <%= f.input :location %>
  <%= f.input :image %>
  <%= f.submit %>
<% end %>

app/views/items/edit.html.erb
<h2>Edit your item</h2>
<%= render "form", item: @item %>

app/views/items/index.html.erb
<h1>All available items</h1>
<p><%= link_to "Offer an item", new_item_path, class: "btn btn-dark" %></p>
<ul class="cards-all-items">
<% @items.each do |item| %>
  <li>
  <div class="card">
    <h3><%= link_to item.name.titleize, item_path(item) %></h3>
    <div class="card-image">
      <% if item.image %>
        <%= link_to (image_tag item.image), item_path(item) %>
      <% else %>
        <p><em><%="no image available"%></em></p>
      <% end %>
    </div>
    <div class="card-info">
      <p><%= item.description %></p>
      <h6>Credit <strong><%= item.credit %></strong></h6>
    </div>
  </li>
</div>
<% end %>
</ul>

app/views/items/new.html.erb
<h2>Offer your item</h2>
<%= render "form", item: @item %>

app/views/items/show.html.erb
<h4><strong><%= current_user.username %></strong> is interested in:</h4>
<br>
<h1><strong><%= @item.name %></strong></h1>
<%= image_tag @item.image, width: "500px" %>
<p><%= @item.description %></p>
<h1><strong><%= @item.credit %> Credits</strong></h1>
<h5>Your credits: <%= current_user.credit_left %></h5>
<br>
<p>Pickup at:</p>
<p><strong><%= @item.location %></strong></p>
<br>
<%= link_to "Back", items_path, class: "btn btn-dark" %>
<%= link_to "Edit", edit_item_path, class: "btn btn-dark" %>
<%= link_to "Remove", item_path(@item), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-dark" %>
<%= link_to "Buy", "#", class: "btn btn-dark" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fleade</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "shared/navbar" %>
  <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Buy, Trade, Swap</h1>
<h3>Your online flea market</h3>

<%= link_to "All items", items_path, class: "btn btn-dark"%>
<%= link_to "Offer an item", new_item_path, class: "btn btn-dark" %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
      <%# <%= link_to "FLEADE", "/" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "/", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag current_user.image, class: "avatar dropdown-toggle", height: "45px", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>